- name: reload sysctl
  become: yes
  command: 'sysctl -p /etc/sysctl.d/*.conf'

- name: rebuild grub
  become: yes
  command: /usr/sbin/update-grub

- name: reload udev
  become: yes
  shell: udevadm control --reload-rules && udevadm trigger

- name: reload sshd
  become: yes
  systemd:
    name: sshd
    state: reloaded

- name: restart networking
  become: yes
  systemd:
    name: networking
    state: restarted

- name: reload network-manager
  become: yes
  systemd:
    name: NetworkManager
    state: reloaded

- name: restart docker
  become: yes
  systemd:
    name: docker
    state: restarted

- name: update initramfs
  become: yes
  shell:
    cmd: update-initramfs -u
  notify: reboot system

- name: reboot system
  become: yes
  reboot:
    reboot_timeout: 100
