version: '3.1'
services:
  cell-logger:
    build:
      context: ../cell-logger
    restart: always
    environment:
      db_user: "avena"
      db_host: "postgres"
      db_database: "avena"
      db_password: "password"
      db_port: "5432"
    depends_on:
      - postgres
    volumes: 
      - /var/run/dbus:/var/run/dbus:rw
      - /data/logs:/data/logs:rw
