name: docker buildx

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
    tags:
      - '*'

env:
  DOCKER_IMAGE_PROD: "isoblue"
  DOCKER_IMAGE_DEV: "isoblue"
  DOCKER_PLATFORMS: "linux/amd64,linux/arm/v7"

jobs:
  docker:
    strategy:
      matrix:
        service:
          - gps2tsdb
          - oada_upload
          - cell_logger
          - can_watchdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Cache docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}
            ${{ runner.os }}-buildx-

      - name: Prepare
        id: prepare
        run: |
          echo 'Porcessing git ref:' $GITHUB_REF
          
          DOCKER_IMAGE=isoblue/${{ matrix.service }}

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/}

            # Make default branch the latest tag
            if [[ $VERSION == ${{ github.event.repository.default_branch }} ]]; then
              VERSION='latest'
            fi

          elif [[ $GITHUB_REF == refs/pull/*/merge ]]; then
            VERSION=${GITHUB_REF#refs/pull/}
            VERSION="pr-${VERSION%/merge}"
            
          elif [[ $GITHUB_REF == refs/remotes/pull/*/merge ]]; then
            VERSION=${GITHUB_REF#refs/remotes/pull/}
            VERSION="pr-${VERSION%/merge}"
            
          else
            echo ::error ::Can not determine version of service -- unexpected job trigger? Stopping.
            exit 1
          fi

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args:: \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg GIT_REF=${GITHUB_SHA::8} \
            --tag ${DOCKER_IMAGE}:${VERSION} \
            ${TAGS} --file services/${{ matrix.service }}/Dockerfile ./services/${{ matrix.service }}

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Docker buildx
        if: success()
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}

      - name: Docker check manifest
        if: success()
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
